### ISSUE TITLE
Implement record submission flow

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#23]
_From @torrin47 on August 31, 2018 23:11_

Upon completion a user will be able to click a submit button that sends the finished document to the EDG team for review and posting to the EDG. How does this work? Do we simply send the json file as an email to edg@epa.gov via server CGI script (python example already implemented for EnviroAtlas) or something similar? Is there any more elegant solution? If we are implementing an ORCID Authentication, could we allow record to be directly posted into EDG for review? If we do, we'd still need some sort of notification.

_Copied from original issue: USEPA/EPA_Environmental_Dataset_Gateway#66_

**Comment by aergul** [comment]
First attempt appeared to be successful:
![image](https://user-images.githubusercontent.com/5661702/48102085-5a1fb800-e1f7-11e8-9da7-e4dfb45fcf39.png)

Nice. Expect many more...

**Comment by torrin47** [comment]
Roger that!  
![image](https://user-images.githubusercontent.com/2127036/48102317-796b1500-e1f8-11e8-90ff-8e5df3ecd8a5.png)

**Comment by aergul** [comment]
Uploaded a somewhat primitive version. Succeeds submitting a record with little entry. Failed on a rather large record with HTTP 404 NOT FOUND. Large record attached. @torrin47 


[4b74aab6-d0ce-456c-a73b-68521dc16e80 (1).json.txt](https://github.com/USEPA/EPA_Non-geo_Metadata_Editor/files/2556292/4b74aab6-d0ce-456c-a73b-68521dc16e80.1.json.txt)

**Comment by torrin47** [comment]
Ok, that's not unexpected for a GET request, but the endpoint should also accept POST - should be an easy switch?

**Comment by aergul** [comment]
Now POSTing, no more 404 which is great. Still getting failure, as in {"status":"failure"}, with above record. It's valid per pod validator but it does have two datasets, is that the problem? @torrin47 

Deployed latest, if you would like to experiment.

**Comment by torrin47** [comment]
I added a basic error message to the response, which helps slightly. The "Not Indexable" message indicates it's not able to find a parameter - in this case I believe it's looking for "metadata" in the payload, but when I look in Chrome dev tools, I'm seeing the raw record as the payload, not referenced as "metadata".  This stackoverflow posting seems to clarify slightly:

https://stackoverflow.com/questions/23118249/whats-the-difference-between-request-payload-vs-form-data-as-seen-in-chrome

form = cgi.FieldStorage() 
metadata = form.getvalue('metadata')

When I test using Postman, I'm able to get it to work with both Content-Type: application/x-www-form-urlencoded and Content-Type: multipart/form-data but all of the elements are necessary.

**Comment by aergul** [comment]
Ah, ok, didn't know it was expecting multi-part form submission. Now it works. At least on this end. Your side?

**Comment by torrin47** [comment]
Yeah, neither did I until we saw the errors.  Working smoothly now, I'm receiving the emails... and realizing that I probably need to work on the formatting to not confuse the sponsors.  
One adjustment, the tool shows a success message following submission, but the Submit to EPA modal stays open - can we have that close if the submission is successful?

**Comment by torrin47** [comment]
Oh, i'm still getting sponsor hardcoded as greene.ana@epa.gov - can we wire that up to epa_contact?  It's not sending to them yet, but I do print out that element for testing.

**Comment by aergul** [comment]
I wasn't sure about what you wanted to with it. Right now sponsor is optional. Do we want to make it mandatory or do we want to keep it optional for validation purposes but required for submit purposes? The latter requiring some custom logic.

**Comment by torrin47** [comment]
I think sponsor is going to be mandatory for external users.  No need for custom logic.

**Comment by aergul** [comment]
Sponsor now mandatory.
Modal closes if submission successful.

**Comment by torrin47** [comment]
Awesome.
