### ISSUE TITLE
Add lookup service for mediatype elements

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#3]
_From @torrin47 on September 24, 2018 17:12_

Several elements (data dictionary, download URL type) have an optional mediatype element associated with a huge domain of MIME types.  Similar to the language lookup, let's allow a user to search for optional types and/or infer the default mediatype from the URL.

_Copied from original issue: USEPA/EPA_Environmental_Dataset_Gateway#84_

**Comment by aergul** [comment]
This is now implemented alongside describedBy element

**Comment by jzichichi** [comment]
Looks like look-up service is working; added my comments regarding floating to the top to the other ticket, so I will move this one over as it appears that the lookup service is working well.

**Comment by torrin47** [comment]
:+1:
