### ISSUE TITLE
Save and load metadata records

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#32]
_From @torrin47 on August 31, 2018 22:46_

A user will be able to save an in-progress document to their local machine in JSON format and load previously saved documents for further editing.

_Copied from original issue: USEPA/EPA_Environmental_Dataset_Gateway#57_

**Comment by aergul** [comment]
Rudimentary file save implemented.
Currently uses doc id for filename. Allow user to enter a name but default to doc id maybe?
Please feel free to test save function with different browsers.
Haven't focused on getting the content up to spec, yet.

**Comment by jzichichi** [comment]
@aergul @torrin47 - I tested this from the perspective of ensuring that fields that were filled out in the form were written to the saved file (not from validation perspective).  From what I can tell, everything written is being saved appropriately.   I will pass this to Torrin to test, unless @aergul  you want this to be in progress for finalizing the format that will be up to spec and can be validated.
