### ISSUE TITLE
Empty elements showing as invalid at pageload

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#37]
There are 5 elements that show as invalid at pageload:  Last Update, Update Frequency, Access Level, Temporal Extent, and Release date. These should have the appropriate "empty" symbols on pageload.

**Comment by aergul** [comment]
Updated the validations for these elements so that their initial state is "empty"

**Comment by jzichichi** [comment]
@aergul - looks better - though temporal extent and release date show orange triangles for me on load, which I think is not supposed to be the case. On that note, the list above includes last update but I think that one is actually mandatory and the current icon is correct? @torrin47?

**Comment by torrin47** [comment]
temporal extent is mandatory, release date is optional.

**Comment by jzichichi** [comment]
@aergul - it looks like you updated this?

**Comment by aergul** [comment]
yes
