### ISSUE TITLE
Rights element is requiring URL for validation

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#38]
Element should validate as plain text.

**Comment by aergul** [comment]
Now looking for min of three words

**Comment by jzichichi** [comment]
@aergul - seems to be requiring 5 words from me.

**Comment by torrin47** [comment]
Validation is good (thanks for the explanation) let's default status icon to optional and only show mandatory when access is set to something other than public.

**Comment by jzichichi** [comment]
@aergul - this appears to be working as described above as well.  Just confirming that this was updated and ready for testing.

**Comment by aergul** [comment]
yes

**Comment by torrin47** [comment]
👍
