### ISSUE TITLE
General review of guidance for fields in user interface

### ISSUE THREAD

**Issue by jzichichi** [USEPA/EPA_Non-geo_Metadata_Editor#40]
Should do a general review and update of guidance that currently shows up for the fields shown in the UI.  Specifically, useful guidance should be added for distribution field(s) that describes different choices and requirements to users.  @torrin47, would you like to take this on or do you prefer that I do so?

**Comment by torrin47** [comment]
I'd like to give this a go - and now that it's in the repo, I'll create a branch for these edits and submit a pull request for their review.

**Comment by jzichichi** [comment]
@torrin47 - sounds great!

**Comment by torrin47** [comment]
Going to try using markdown in guidance, we'll see how it looks.  Newline characters are going to be the least fun part.

**Comment by aergul** [comment]
merged
