### ISSUE TITLE
The keywords elements are showing "valid" when empty

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#41]
I think we want to enforce the selection of at least one keyword/tag from each of the dropdowns, so on pageload the elements should show the mandatory/empty icon.

**Comment by aergul** [comment]
addressed

**Comment by jzichichi** [comment]
@torrin47 @aergul - this appears to be addressed.  I was wondering if the EPA Organization keywords should be removed?

**Comment by torrin47** [comment]
Validation looks great, and I'm puzzled on the EPA Organization Keywords.  That's not one we should be showing to extramural folks, it's a phase 2 internal element. I guess I've been overlooking it for some time. Definitely good to remove for now.
