### ISSUE TITLE
Infer mediatype from URL

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#43]
If a URL has an optional mediatype element associated with it, the editor should check the end of the URL for a file extension that matches the list of mediatypes, and if it matches one, it should default to that value.

**Comment by jzichichi** [comment]
Appears to be working for me.  For example, if I enter http://test.csv, csv is selected,  same for .html, same for .txt.  Moving for @torrin47  to test.

**Comment by aergul** [comment]
Implemented for describedBy elements as well now
