### ISSUE TITLE
Save File - Capture all inputs from user in saved file

### ISSUE THREAD

**Issue by jzichichi** [USEPA/EPA_Non-geo_Metadata_Editor#44]
Save process should capture all user inputs appropriately.

**Comment by jzichichi** [comment]
@torrin47 - @aergul and I broke save down into multiple tickets to address separate portions of the process.  This portion is ready for testing whenever you are ready.

**Comment by torrin47** [comment]
Ok, the save file piece works, though the preview function seemed to be having issues. Will capture validation notes in other tickets.

**Comment by aergul** [comment]
I had briefly deployed a "work in progress" version to dev. I think you came testing during that period @torrin47 . A new version is up now.
