### ISSUE TITLE
Save File - Saved file should be compliant with POD metadata spec

### ISSUE THREAD

**Issue by jzichichi** [USEPA/EPA_Non-geo_Metadata_Editor#45]
Should validate according to https://labs.data.gov/dashboard/validate

**Comment by torrin47** [comment]
My initial validation has so many different notes, I'm going to break them out into separate tickets.

**Comment by aergul** [comment]
Compliance related tickets addressed. 
Additionally, we are now pruning empty elements from the output which should also help with compliance.

**Comment by jzichichi** [comment]
Filled in all required fields and POD validator gave me a 100%.  Moving over for @torrin47 to review.

**Comment by torrin47** [comment]
Perfect.
