### ISSUE TITLE
Saved record needs to be placed in json context

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#51]
When saving, everything so far needs to be wrapped inside a parent element:

{
  "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
  "@id": "https://replace.me",
  "@type": "dcat:Catalog",
  "conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
  "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
  "dataset": [{everything we're capturing in the tool.JSON}]
}

the @id element is tough - it's supposed to be the URL where the record is available for download, but these authors won't know that a priori, so the EDG team will fill that in later, or maybe we'll set it to a static value that can work for all these external records.

**Comment by aergul** [comment]
Placed in json context now.

**Comment by jzichichi** [comment]
@aergul - looks good.  Moving over
