### ISSUE TITLE
All tags should be dumped into a single array

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#52]
We require users to pick tags from several lists, but in the output metadata all tags get dumped into a single array: keyword.  This makes it a little more complicated when reloading saved records, as there are a couple of tags that appear in multiple picklists - the best example is the tag "environment". Do we mark both picklists as selected, or just one?

**Comment by aergul** [comment]
All tags under keywords when output. Dupes eliminated.

We will deal with the "which picklist" problem on the load epic.

**Comment by jzichichi** [comment]
confirmed. Moving to @torrin47 column

**Comment by torrin47** [comment]
👍
