### ISSUE TITLE
Publisher needs to output object, not string

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#53]
We're currently producing:

    "publisher": "Extramural Publisher's Organization"

but the specification requires:

"publisher": {
  "@type": "org:Organization",
  "name": "Extramural Publisher's Organization"
}

The spec also allows for an organizational hierarchy using subOrganization objects, but we're not going to include that option in this tool, at least not at this time.

**Comment by aergul** [comment]
outputting object

**Comment by jzichichi** [comment]
@aergul - I see the new object created but it looks like name is actually recording user input for organization.

**Comment by aergul** [comment]
I believe the intent is to write out user provided organization.
@torrin47 ?

**Comment by torrin47** [comment]
Is good.
