### ISSUE TITLE
References should be Array of URLs, not string

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#54]
For the MVP we might be ok with just wrapping our single URL string in an array:

"references": ["https://references.url"],

but we should anticipate allowing users to manage multiple URLs in a manner similar to Distribution.

**Comment by aergul** [comment]
References is an array now. 
Please create new ticket if you would like to support multiple URLs

**Comment by jzichichi** [comment]
@aergul - references array verified.  Moving over
