### ISSUE TITLE
Hardcode bureauCode and programCode 

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#55]
For now to minimize confusion on validation, let's hard code the following bureauCode and programCode values on all extramural records:

			"bureauCode" : [
				"020:00"
			],
			"programCode" : [
				"020:098"
			]

**Comment by aergul** [comment]
hardcoding now

**Comment by jzichichi** [comment]
@aergul @torrin47 - confirmed that seeing these output as hard coded. Moving over for @torrin47 to review.

**Comment by torrin47** [comment]
all good with 020:000, thanks!
