### ISSUE TITLE
Submit button

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#57]
Per our discussion today, could we add a submit button to float next to the menu button at lower right? I was thinking this icon might be appropriate:

https://fontawesome.com/icons/paper-plane?style=solid

The mouseover text would be "Submit" and it would trigger a confirmation modal with the following text:

"Clicking Submit will send your metadata record to EPA's metadata team for review. You will receive confirmation via email if it is accepted into EPA's metadata inventory. Please contact edg@epa.gov if you wish to make changes to your record at any point int he future."  Submit / Cancel

**Comment by aergul** [comment]
Addressed

**Comment by jzichichi** [comment]
@aergul this seems to work well. The only question I had is shouldn't we make the button the same color as the other mandatory but missing elements?  It seems like that would be more consistent to me.  Other than that, the functionality of this worked great for me.  Will pass to @torrin47 for review.

**Comment by aergul** [comment]
@jzichichi I picked the colors based on a two-state model (1- Everything good to submit 2- Something needs to be resolved) and picked universal colors for those (green/red).

If we step out of that scheme then maybe we should follow along with the four-state model we use for individual elements? Although gray would not prevent submitting and it might effectively be three colors in practice.

**Comment by jzichichi** [comment]
@aergul - I'm open to whatever makes the most sense. It just was something I had noted and figured I'd mention it. Perhaps it doesn't need to align with the orange of the other elements; maybe that would just confuse.  Open to preference all around.

**Comment by torrin47** [comment]
I think I'm good with the fact that the red/green binary departs from the rest of the schema, though maybe we should be cautious about using only color as the indicator for the red/green colorblind.  Still, I'd leave it as-is and see what the testers say.

**Comment by aergul** [comment]
I had actually experimented with the tooltip displaying validity info but felt it makes the feedback (you get when click submit) redundant. I could put it back in or we could experiment with other visual indicators (size/shape of button, different icons, etc.)
