### ISSUE TITLE
Add two new fields to verify legitimacy of extramural researcher

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#59]
Grant Number:
Please enter the grant number under which you performed the research associated with this dataset. If you are not an EPA Grantee, please describe the nature of your affiliation with the EPA.

EPA Contact:
Please enter the email address of your EPA grant manager, sponsor, or other point of contact who can verify your relationship with the EPA.

**Comment by aergul** [comment]
addressed
