### ISSUE TITLE
Load metadata: UI

### ISSUE THREAD

**Issue by aergul** [USEPA/EPA_Non-geo_Metadata_Editor#61]

**Comment by aergul** [comment]
Similar to save UI, we now have a load UI to preview the file being loaded. We could communicate any file issues here (separate epic).

**Comment by jzichichi** [comment]
@aergul - I like the interface and the fact that you can see the content being loaded.  My default screen - before I select a file to load -  is very narrow and long (see below).  Not a huge deal but just seems odd.  Only other question I had is that i am not sure if the pencil is an intuitive button for the 'load' process.  I am not sure if that's just me. Maybe it doesn't matter.  Just a thought.  I am passing this to @torrin47 for his input as well.
![load](https://user-images.githubusercontent.com/13878970/47658694-c9e3d200-db69-11e8-8b90-f861835f4abc.png)
