### ISSUE TITLE
Load metadata: handle unexpected elements

### ISSUE THREAD

**Issue by aergul** [USEPA/EPA_Non-geo_Metadata_Editor#67]

**Comment by aergul** [comment]
Implemented for non-repeating elements.
Does anyone see utility of implementing this for repeating elements?

**Comment by jzichichi** [comment]
@torrin47 - passing along for your review

**Comment by torrin47** [comment]
Can you be more clear about the definition of an unexpected occurrence of a repeating element?  Is that when the same key appears twice in the JSON? Or an expected key has repeating items in an array?

**Comment by aergul** [comment]
@torrin47 sorry for the confusion. 
These would be unexpected elements inside repeating elements such as distribution. No rush, we can discuss on weekly if unclear.

**Comment by torrin47** [comment]
Ok, got it.  Uploaded this:

"distribution" : [{
					"@type" : "dcat:Distribution",
					"title" : "U.S. EPA Enterprise Data Inventory",
					"downloadURL" : "https://www.epa.gov/data.json",
					"mediaType" : "application/json",
					"conformsTo" : "https://project-open-data.cio.gov/v1.1/schema/",
					"format" : "Project Open Data Schema 1.1 JSON"
				},{
                "reallyUnexpectedElement":"what is this doing here?"
                }
]

and the result was this:

"distribution": [
                {
                    "@type": "dcat:Distribution",
                    "downloadURL": "https://www.epa.gov/data.json",
                    "format": "Project Open Data Schema 1.1 JSON",
                    "title": "U.S. EPA Enterprise Data Inventory",
                    "mediaType": "application/json",
                    "conformsTo": "https://project-open-data.cio.gov/v1.1/schema/"
                },
                {
                    "@type": "dcat:Distribution",
                    "accessURL": ""
                }
            ]

Which seems perfectly acceptable to me.

**Comment by torrin47** [comment]
👍
