### ISSUE TITLE
Load metadata: populate distribution element

### ISSUE THREAD

**Issue by aergul** [USEPA/EPA_Non-geo_Metadata_Editor#69]
It's a big section of metadata so it gets its own ticket

**Comment by jzichichi** [comment]
Loading of distribution content did not show up with this file:

[7afb93f3-70e8-46c6-b8e7-a9bda388a12f.json.txt](https://github.com/USEPA/EPA_Non-geo_Metadata_Editor/files/2540727/7afb93f3-70e8-46c6-b8e7-a9bda388a12f.json.txt)

**Comment by aergul** [comment]
This is because #65 is not implemented yet.
Can you please try with a complete metadata record?

**Comment by jzichichi** [comment]
better!  I noticed something that seemed unusual tho. I load the file, it loads to the distribution elements, but if I try to then edit those loaded entries in that section, some seem to go missing.  See the following showing this sequence:

![load_distribution1](https://user-images.githubusercontent.com/13878970/47959031-de7ffa00-dfaf-11e8-8c8b-94d430998a1c.png)
![load_distribution2](https://user-images.githubusercontent.com/13878970/47959032-de7ffa00-dfaf-11e8-8328-58bd5e8c5254.png)
![load_distribution3](https://user-images.githubusercontent.com/13878970/47959033-df189080-dfaf-11e8-9cbc-651c06c871c4.png)

**Comment by aergul** [comment]
Good catch, fixed.

**Comment by aergul** [comment]
I apologize, I think I forgot to deploy. Please try again.

**Comment by jzichichi** [comment]
Better tho format is getting lost now.  Take a look.
![untitled](https://user-images.githubusercontent.com/13878970/48041229-4a966580-e14a-11e8-8fb8-ad3fad264a94.png)

**Comment by aergul** [comment]
Format fixed

**Comment by jzichichi** [comment]
@aergul - looks great!  I will pass to @torrin47 for review.

**Comment by torrin47** [comment]
👍
