### ISSUE TITLE
Submission status/validation

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#76]
We're going to use the submission button as the master status indicator. We'll go with subtle at first - inactive if there are any invalid elements or missing mandatory elements, active for submission if all mandatory elements are complete and valid and there are no invalid elements.

We could also include hovertext explaining why the button is inactive:
"Please complete all mandatory elements and ensure all completed elements are valid before submitting".

**Comment by aergul** [comment]
#57 had different mouseover instruction so instead we give additional info when submit button is clicked

**Comment by jzichichi** [comment]
@aergul, worked well.  Comments related to icon color noted in #57

**Comment by torrin47** [comment]
I'm ok with it, but curious to see how users react. The error/feedback popups are nice.
