### ISSUE TITLE
Data Quality Element should have a third option that represents no selection

### ISSUE THREAD

**Issue by jzichichi** [USEPA/EPA_Non-geo_Metadata_Editor#78]
Three options discussed "Yes", "No", "Don't Know".  "Don't Know" may be replaced by something more intuitive?

Object should be implemented that allows for 3 options; "Don't Know" should have no value written to metadata.

**Comment by aergul** [comment]
Adressed

**Comment by jzichichi** [comment]
@aergul - I like it - I will move over for @torrin47 to review

**Comment by torrin47** [comment]
Works for me, thanks!
