### ISSUE TITLE
Handling files with multiple records

### ISSUE THREAD

**Issue by jzichichi** [USEPA/EPA_Non-geo_Metadata_Editor#79]
@torrin47, the current implementation allows user to load file with more than one record in it.  User is able to edit first record; other content is saved but not shown to user in the edit interface, but it is shown when the view the raw json content to be saved.  What happens if user submits this type of record to EPA?   Will this cause problems or confusion?

**Comment by aergul** [comment]
Only metadata for first dataset included in submission now.

**Comment by jzichichi** [comment]
@aergul - saves first record only for both submission and save functions?  I tested with a pre-existing OLEM record and it worked great - retaining only first record - but for both save and submit.  Guessing that's intentional.  Wanted to be sure.

**Comment by aergul** [comment]
The intention is to keep all for save but submit only the first. If that's not the case then it is a bug.

**Comment by jzichichi** [comment]
@aergul - OK I thought I had remembered discussing it that way. It seems to me save chops it off.  See attached files. OSWER-EF is the original and the second is the saved (with some edits from the editor in there.

Maybe there is an issue with the formatting in the original - it's one that was handed to me a few months ago and I was editing it via notepad - the records contained in it were accepted by EDG..

[E3C724A0-A2DB-4B43-BC07-A7A2B5671E2F.txt](https://github.com/USEPA/EPA_Non-geo_Metadata_Editor/files/2577188/E3C724A0-A2DB-4B43-BC07-A7A2B5671E2F.txt)
[OSWER-EF.txt](https://github.com/USEPA/EPA_Non-geo_Metadata_Editor/files/2577189/OSWER-EF.txt)

**Comment by aergul** [comment]
@jzichichi while submit and save operated on a copy of the document rather than the original, they both operated on the same copy. Now we use a fresh copy sans datasets other than first during submission.

**Comment by jzichichi** [comment]
@aergul BETTER!!! Moving over for @torrin47 to review

**Comment by torrin47** [comment]
Is great, thanks!
