### ISSUE TITLE
Add captcha to submission modal

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#80]
still trying recaptcha

**Comment by jzichichi** [comment]
I'm not sure if I'm interpreting the content on the screen correctly but it looks like the words are getting cut off slightly...

![untitled](https://user-images.githubusercontent.com/13878970/48683970-94853f80-eb7d-11e8-820f-51d5c74a75ba.png)

**Comment by aergul** [comment]
I went for fixed size padding now, ditching the framework's dynamic padding.
