### ISSUE TITLE
Date Elements Punchlist

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#87]
The calendar widget doesn't work in IE.  If there are barriers to getting it working in IE, it would be acceptable to fall back to a field that simply accepts manually entered in a consistent format (and validates). 

Can we relax the validation to permit YYYY or YYYY-MM as valid entries instead of requiring YYYY-MM-DD?

**Comment by aergul** [comment]
After checking out several calendar widgets I decided to go with simple input fields with enough cues and validation for the user. Each widget had some kind of functional or visual issue in IE, including supporting the year and year/month only format.

Ready for QA.

**Comment by jzichichi** [comment]
@aergul - the implementation looks good to me; I will pass along to see what @torrin47 has to say.

**Comment by torrin47** [comment]
I love the Occam's Razor approach. Dates aren't that tough to type in, and in this workflow, a calendar widget might often be more work the further the relevant dates get from "today".  The cues for optional month and day are clear to me, but might be a little obscure to an end user - I think we'll want to add a sentence to the guidance for each date field spelling this out. I have a vague memory of tidying up this language, but now I can't find it anywhere, even in the "before" version of the tech spec, so I must just be getting old.  One minor validation bug, I was able to get "Last Update" to show as valid with any character. I know this validation is complicating by its coupling with "Update Frequency" but if we can get it to require a full YYYY, it'd help.  Thanks!

**Comment by aergul** [comment]
We now enforce that the last update value is a valid date

**Comment by jzichichi** [comment]
@aergul @torrin47 - last update validation appears correct to me.

**Comment by torrin47** [comment]
Solid.
