### ISSUE TITLE
EPA Grant Punchlist

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#88]
Pending final decision, we need to:

- Change name to EPA Agreement
- make value mandatory
- Add picklist allowing user to specify agreement type: Grant, Contract, Cooperative Agreement, Inter-Agency Agreement, or other.

**Comment by aergul** [comment]
The element we used before (epa_grant_no) is now replaced with epa_agreement_type and epa_agreement_no. FYI.

Ready for QA.

**Comment by jzichichi** [comment]
@aergul - this looks good to me.  Moving over for @torrin47 to review

**Comment by torrin47** [comment]
Looks great, would just like to request a tiny tweak. Could we change the wording to:

"Please select EPA agreement type"
and 
"Please enter EPA agreement number or description"

**Comment by aergul** [comment]
Wording tweaked

**Comment by jzichichi** [comment]
@aergul @torrin47 - wording updates look correct to me.

**Comment by torrin47** [comment]
Great.
